[build-system]
requires = ["setuptools>=61", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

[project]
name = "koopomics"
version = "0.0.1"
authors = [
    {name = "Philipp Trinh", email = "trinh.philipp@hotmail.com"},
]
description = "Koopman Model for OMICS data"
license = {text = "Apache 2.0"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
requires-python = ">=3.10, <3.11"
dependencies = [
    "torch==2.2.2",
    "matplotlib==3.9.2",
    "numpy==1.26.4",
    "scikit-learn==1.5.2",
    "umap-learn==0.5.6",
    "pandas==2.2.3",
    "plotly==5.24.1",
    "seaborn==0.13.2",
    "torchvision==0.17.2",
    "wandb==0.18.5"
]
[project.readme]
file = "README.md"
content-type = "text/markdown"

[tool.setuptools]
include-package-data = true
