_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
E_dropout_rate_1:
    value: 0.33361760376205923
E_dropout_rate_2:
    value: 0.5762595947537265
E_layer_dims:
    value: 264,2000,2000,100
batch_size:
    value: 12
dl_structure:
    value: random
epochs:
    value: 156
grad_clip:
    value: 0.41320741218645823
learning_rate:
    value: 0.00034562617097034343
learning_rate_change:
    value: 0.219030242269201
max_Kstep:
    value: 1
op_reg:
    value: skewsym
operator:
    value: invkoop
weight_decay:
    value: 0.01527829250595139
