name: koopomics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - matplotlib=3.9.2
  - scikit-learn=1.5.2
  - umap-learn=0.5.6
  - pandas=2.2.3
  - plotly=5.24.1
  - seaborn=0.13.2
  - numba
  - ipython
  - ipywidgets
  - jupyter
  - captum
  - llvm
  - llvmlite
  - pip:
    - torch==2.0.0
    - torchvision==0.15.1
    - wandb==0.18.5
    - torchviz