_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
Kmatrix_modification:
    value: nondelay
activation_fn:
    value: leaky_relu
dataset:
    value: 'pregnancy dataset: Liang L, Rasmussen MH, Piening B, Shen X, Chen S, RÃ¶st H, Snyder JK, Tibshirani R, Skotte L, Lee NC, Contrepois K, Feenstra B, Zackriah H, Snyder M, Melbye M. Metabolic Dynamics and Prediction of Gestational Age and Time to Delivery in Pregnant Women. Cell. 2020 Jun 25;181(7):1680-1692.e15. doi: 10.1016/j.cell.2020.05.002. PMID: 32589958; PMCID: PMC7327522.'
decayEpochs:
    value:
        - 30
        - 60
        - 90
        - 120
        - 150
        - 180
        - 210
        - 240
        - 270
        - 300
        - 330
        - 360
        - 390
        - 410
        - 440
        - 470
        - 500
embedding:
    value: ff_ae
embedding_dim:
    value:
        - 264
        - 200
        - 150
        - 50
embedding_input_dropout_rate:
    value: 0.3
embedding_latent_dim:
    value: 50
embedding_num_hidden_layer:
    value: 2
embedding_num_hidden_neurons:
    value: 200
epochs:
    value: 600
feature_selected:
    value: false
grad_clip:
    value: 1
interpolated:
    value: true
learning_rate:
    value: 0.001
learning_rate_change:
    value: 0.2
loss_weights:
    value:
        - 1
        - 0.5
        - 1
        - 1
        - 0.01
        - 0
mask_value:
    value: -2
max_Kstep:
    value: 1
min_max_scaled_-1_1:
    value: true
min_max_scaled_0_1:
    value: false
num_metabolites:
    value: 264
operator:
    value: invkoop
optimizer:
    value: adam
outlier_rem:
    value: true
robust_scaled:
    value: true
weight_decay:
    value: 0.01
