_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
E_layer_dims:
    value: 264,1500,1500,50
batch_size:
    value: 6.846875247146579
dl_structure:
    value: random
max_Kstep:
    value: 1
