method: bayes
metric:
  goal: minimize
  name: combined_test_loss
parameters:
  E_dropout_rate_1:
    distribution: uniform
    max: 1
    min: 0
  E_dropout_rate_2:
    distribution: uniform
    max: 1
    min: 0
  E_layer_dims:
    distribution: categorical
    values:
    - 247,500,10
    - 247,500,200,10
    - 247,1000,3
    - 247,2000,3
    - 247,500,500,10
    - 247,500,500,3
    - 247,100,100,3
  E_overfit_limit:
    distribution: uniform
    max: 1
    min: 0.1
  activation_fn:
    distribution: categorical
    values:
    - leaky_relu
    - sine
    - gelu
    - swish
  augment_by:
    distribution: categorical
    values:
    - noise
    - noise, scale
    - noise, shift
    - noise, scale, shift
    - scale
    - shift
  backpropagation_mode:
    distribution: categorical
    values:
    - full
    - stepwise
  batch_size:
    distribution: int_uniform
    max: 800
    min: 5
  delay_size:
    distribution: int_uniform
    max: 5
    min: 2
  learning_rate:
    distribution: log_uniform_values
    max: 0.01
    min: 1.0e-06
  learning_rate_change:
    distribution: uniform
    max: 0.9
    min: 0.1
  loss_weights:
    distribution: categorical
    values:
    - 1,1,1,1,1,1
    - 1,1,1,1,0,0
    - 1,0.5,1,0,0.01,0.1
    - 1,0.5,1,0,0.00001,0.01
    - 1,0.05,0.01,0,0.00001,0.01
    - 1,0.005,0.01,0,0.000001,0.0001
  num_augmentations:
    distribution: int_uniform
    max: 3
    min: 1
  num_decays:
    distribution: int_uniform
    max: 10
    min: 3
  num_epochs:
    distribution: int_uniform
    max: 5000
    min: 1000
  op_bandwidth:
    distribution: int_uniform
    max: 10
    min: 1
  op_reg:
    distribution: categorical
    values:
    - banded
    - nondelay
    - skewsym
    - None
  operator:
    distribution: categorical
    values:
    - invkoop
  sweep_name:
    value: outer_4
  training_mode:
    distribution: categorical
    values:
    - full
    - modular
  weight_decay:
    distribution: log_uniform_values
    max: 0.01
    min: 1.0e-06
